<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ApplicationDefinition Remove="App.xaml" />
		<ApplicationDefinition Include="App.xaml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Logic\Logic.csproj" />
	</ItemGroup>

</Project>